name: Docker Image CI

on:
  push:
    tags:
      - v*

env:
  DOCKER_HUB_NAMESPACE: bingdian
  ALIYUN_DOCKER_NAMESPACE: bingdian
  IMAGE_NAME: bingdian/alinode

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file alinode/bullseye-slim/Dockerfile --tag $IMAGE_NAME

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # 从 tag 名字中替换 v- 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          echo $IMAGE_NAME=$IMAGE_NAME
          echo VERSION=$VERSION
          
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          
          # 进行 push
          docker push $IMAGE_NAME:$VERSION

      - name: Log in to Aliyun Dokcer registry
        run: echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login registry.cn-shenzhen.aliyuncs.com --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}"  --password-stdin

      - name: Push image to Aliyun Dokcer registry
        run:  |
          # 将所有的大写字母转为小写
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # 从 tag 名字中替换 v- 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME ${{ secrets.ALIYUN_DOCKER_REGISTRY}}/$IMAGE_NAME:$VERSION
          
          # 进行 push
          docker push ${{ secrets.ALIYUN_DOCKER_REGISTRY}}/$IMAGE_NAME:$VERSION
